### ISSUE TITLE
Remote server problem with ufinder

### ISSUE THREAD

**Issue by trmrsh** [StuartLittlefair/ufinder#1]
Hi Stu, Matthew and I are both having a problem with ufinder. A warning panel comes up in a red font talking about no answer from the remote server. I hope this message will include an attachment to show what I mean although I am not sure how attachments work in github. It's a critical problem as we can't generate any FCs for Matthew's imminent run.

![ufinder-error](https://user-images.githubusercontent.com/983896/47642719-445c2400-db61-11e8-9960-6839009ed266.png)

**Comment by StuartLittlefair** [comment]
There’s nothing I can do about this Tom,

The Aladin service is down at the moment.

**Comment by StuartLittlefair** [comment]
Is this working yet? I'm having no problem from my laptop.

**Comment by trmrsh** [comment]
Ah OK, yes it is working now. Sorry for the bother. I wondered if this was the case but Matthew had been having it since Friday so I thought it might be more permanent.

tom
